server:
  port: 8090
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          min-partition-count: 3
          replication-factor: 1
        bindings:
          kafka-poc:
            consumer:
              start-offset: earliest
      bindings:
        kafka-sender-topic:
          destination: kafka.spring.poc
          content-type: application/json